version: "3"
services:
  mlflow:
    build: ./docker_images/mlflow
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
#    volumes:
#      - "/path/to/google_credentials.json:/path/to/google_credentials.json"
    command: "mlflow server --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} --default-artifact-root ${MLFLOW_DEFAULT_ARTIFACT_ROOT} --host 0.0.0.0 --port 5000"
    restart: always
  nginx:
    build: ./docker_images/nginx
    environment:
      - NGINX_BASIC_AUTH_USER=${NGINX_BASIC_AUTH_USER}
      - NGINX_BASIC_AUTH_PASS=${NGINX_BASIC_AUTH_PASS}
    ports:
      - 80:80
    restart: always

  # compute engineからcloud sqlに接続する場合
#  cloudsqlproxy:
#    image: gcr.io/cloudsql-docker/gce-proxy:1.12
#    command: /cloud_sql_proxy -instances=${CLOUDSQL_INSTANCES}
